export enum OrderStatus {
	PENDING = 'PENDING',
	CONFIRM = 'CONFIRM',
	DELIVERING = 'DELIVERING',
	CANCELLED = 'CANCELLED',
	READY_FOR_COLLECTION = 'READY_FOR_COLLECTION',
	// PARTIAL_PAID = 'PARTIAL_PAID',
	REFUND = 'REFUND',
	COMPLETED = 'COMPLETED',
	EXPIRED = 'EXPIRED',
	PENDING_PAYMENT = 'PENDING_PAYMENT',
}

export enum OrderType {
	NORMAL = 'NORMAL',
	ADHOC = 'ADHOC',
}

export enum PaymentType {
	STRIPE = 'STRIPE',
	HITPAY = 'HITPAY',
}

export enum ExportType {
	MASTER = 'MASTER',
	PACKING = 'PACKING',
	DELIVERY = 'DELIVERY',
	WHOLECAKES = 'WHOLECAKES',
	PRODUCT_SOLD = 'PRODUCT_SOLD',
}
